name: Extrair temas.zip

on:
  push:
    paths:
      - "temas.zip"

jobs:
  unzip-temas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extrair temas.zip
        run: |
          unzip -o temas.zip -d temas

      - name: Commit e Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add temas
          git commit -m "Extra√≠do temas.zip"
          git push || echo "Nada para enviar"
